version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Release
- Debug

cache:
- build/lib -> appveyor.yml

before_build:
- cmd: >-
    git submodule update --init --recursive
    
    mkdir build || VER>NUL
    
    cd build
    
    cmake -G "Visual Studio 15 2017 Win64" ../
    
    dir 
    
build:
  project: build/Games_CW.vcxproj
  parallel: true
  verbosity: minimal
  
after_build:
- cmd: >-
    7z a Games_CW%CONFIGURATION%_win64.zip %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/Games_CW.exe %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/*.dll  %APPVEYOR_BUILD_FOLDER%/build/bin/%CONFIGURATION%/**/*
      
    dir
    
    for %%a in (*.exe) do ren "%%~a" "%%~na_%CONFIGURATION%_win64%%~xa"
    
    dir
    
artifacts:
  - path: build/*.zip
    name: Games_CW.zip